name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build
        run: mvn clean package

#      - name: Get version from pom.xml
#        id: get_version
#        run: echo "::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)"

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: Multiple-*.jar

  publish:
    runs-on: windows-latest
    needs:
      - build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: release/

      - name: dir
        run: dir && dir release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/*
        env:
          GITHUB_TOKEN: ${{ secrets.MULTIPLE_ACCESS_TOKEN }}